### ISSUE TITLE
Building Qt5 on the RPI3 B+

### ISSUE THREAD

**Issue by varoOP** [koendv/qt5-opengl-raspberrypi#3]
I have tried cross-compiling and it hasn't worked. Building it natively on the RPI 3 B+ with qtwebengine is not possible for me because the memory isn't enough and my SD card is too small for a proper swap. 
I think your method of using a chroot on raspbian may work. 
I don't understand what the difference would be between building for RPI4 / RPI 3 if the image is the same..

**Comment by koendv** [comment]
On Sat, 06 Jun 2020 01:11:36 -0700
varoOP <notifications@github.com> wrote:

> I have tried cross-compiling and it hasn't worked. Building it
> natively on the RPI 3 B+ with qtwebengine is not possible for me
> because the memory isn't enough and my SD card is too small for a
> proper swap. I think your method of using a chroot on raspbian may
> work. I don't understand what the different would be between building
> for RPI4 / RPI 3 if the image is the same..
> 


If your memory is too small, you can always swap over the network.
- mount a disk over nfs
- on the nfs disk, allocate a file, eg. fallocate -l 8g swapfile
- make the file swappable: mkswap swapfile
- do a swapon of this file, and a swapoff of the (standard) swap in
  flash.
- start compiling. You will need patience.

Also, reduce memory requirements: better to use "make" than "make -j4".
Look at the hint to edit "ninja" : better "ninja -j1" for you.

Lastly: how about buying a 8gb raspberry 4?

koen

**Comment by varoOP** [comment]
Set it to build with your suggestions. Woke up this morning to see the little old ninja subcommand failed error. :(

**Comment by koendv** [comment]
Try  changing the ninja option in the Makefile to:
```
build-qt/qtwebengine/src/3rdparty/ninja/ninja -j1 -v -C
```
If restricting the build to 1 compilation at a time does not work, it doesn't work.
