### ISSUE TITLE
No themes found in installation error

### ISSUE THREAD

**Issue by jhihn** [koendv/qt5-opengl-raspberrypi#6]
After a `make install` and trying to run qtcreator, I got:
```
Warning: No themes found in installation:  "/usr/share/qtcreator/themes"
Segmentation fault
```

I fixed it with:
`sudo cp -r share /usr`

**Comment by koendv** [comment]
OK. That works. Alternatively, I've compiled qt-creator 4.14.1 against qt 5.15.2. It's in Releases. Can you install that and take it for a test drive?

**Comment by jhihn** [comment]
Will do.

**Comment by jhihn** [comment]
So it's installing a clang tool chain is that expected?
It did not make a menu item on the pi menu.
Using the qtcreator.sh,
When opening a project, it got a 
`Project ERROR: Cannot run compiler clang++. Giving up`

But my qmake && make run just fine with gcc

**Comment by koendv** [comment]
On Fri, 19 Mar 2021 12:40:51 -0700
jhihn ***@***.***> wrote:

> So it's installing a clang tool chain is that expected?
> It did not make a menu item on the pi menu.
> Using the qtcreator.sh,
> When opening a project, it got a 
> `Project ERROR: Cannot run compiler clang++. Giving up`
> 
> But my qmake && make run just fine with gcc
> 
> 

OK. You're right. I'll fix this.

koen

**Comment by koendv** [comment]
OK, done. Re-compiled with gcc only.

**Comment by jhihn** [comment]
Works! I was able to remove QtC, clang, install the newer release of QtC, and compile my project successfully.

**Comment by koendv** [comment]
OK, thanks. I'll close the issue.
