### ISSUE TITLE
Issue * failed to add service - already in use?

### ISSUE THREAD

**Issue by DanielVolt** [koendv/qt5-opengl-raspberrypi#7]
Hey,

I've installed the two packages accordingly but get this following error:

pi@raspberrypi:~ $ qtcreator
* failed to add service - already in use?

Any idea why i'm getting the failed to add service? Even when trying to run QT apps.

**Comment by koendv** [comment]
On Thu, 13 May 2021 18:26:48 -0700
DanielVolt ***@***.***> wrote:

> Hey,
> 
> I've installed the two packages accordingly but get this following
> error:
> 
> ***@***.***:~ $ qtcreator
> * failed to add service - already in use?
> 
> Any idea why i'm getting the failed to add service? Even when trying
> to run QT apps.
> 

What happens if you comment out the following line in /boot/config.txt ?
dtoverlay=vc4-fkms-v3d

koen

**Comment by DanielVolt** [comment]
Hey Koem,

still getting the same error. 

pi@raspberrypi:~ $ qtcreator
* failed to add service - already in use?

**Comment by DanielVolt** [comment]
another question though: is it possible to run a QT app straight on framebuffer using this?

**Comment by koendv** [comment]
The only goal was running "OpenGL Desktop" applications on "OpenGL
Embedded Systems " video hardware.
This is the config summary of the Qt library used:

https://github.com/koendv/qt5-opengl-raspberrypi/blob/master/qt_config_summary.txt

I think you'll have to build your own Qt library.
