### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by Haarolean** [koendv/qt5-opengl-raspberrypi#8]
Hey, would be nice to have arm64 package available as well :)
 
I'm using qt as a dependency in this [project](https://github.com/glensc/raspberry-pi-plex-media-player) and can't get a compatible build on my rpi4.

**Comment by koendv** [comment]
OK. This surprises me. What goes wrong when you use the qt5 libraries supplied with 64-bit raspbian? 

I've tried compiling plex, but the build loops with 'Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt to plexmediaplayer-qt-206-hash.txt...'.

**Comment by Haarolean** [comment]
The thing is I'm building it via this [dockerfile](https://github.com/glensc/raspberry-pi-plex-media-player/blob/main/Dockerfile), which actually build everything upon debian buster and downloads your compiled deb package, which is incompatible if I build it for arm64.

**Comment by Haarolean** [comment]
I understand it might've been a good idea to use qt libraries present on the host machine itself for the build, but the thing is I'm building it via docker to keep the host machine clean of dependencies.

**Comment by koendv** [comment]
On 32-bit raspberry pi os, I recompiled qt because opengl functionality was missing. On the 64-bit raspberry pi os I have not felt such need. So far, the supplied qt library seems to work fine.
Also, on the rpi, if a library provides hardware video support, I'd take it.

**Comment by Haarolean** [comment]
I was just trying to find suitable one for building it within a docker container on my machine. Thanks for your help.
